controller_manager:
  ros__parameters:
    update_rate: 100  

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController  
    joints:
      - base_link_joint  
    state_publish_rate: 50
    command_interfaces:
      - velocity
    allow_partial_joints_goal: true
